# FROM nginx:stable-alpine

# LABEL maintainer = "Lee In Seok<dlstjr9068@gmail.com>"
# LABEL app="development-support-backend"

# COPY nginx.conf /etc/nginx/conf.d/default.conf
# COPY dist/ /usr/share/nginx/html

# EXPOSE 3000
# CMD ["nginx", "-g", "daemon off;"]
