# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI_Development-Support

on:
  push:
    branches: ["release"]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.15.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: frontend npm ci and build
        run: npm ci
        working-directory: ./frontend

      - name: backend npm install
        run: npm ci
        working-directory: ./backend

      - name: frontend npm build
        run: npm run build --if-present
        working-directory: ./frontend

      - name: backend npm build
        run: npm run build --if-present
        working-directory: ./backend

      - name: SSH Action
        env:
          RUNNER_TRACKING_ID: "" # background 로 띄워둔 서버도 같이 닫히게 된다. 비공식적인 부분이지만, 위 값을 등록해서 이를 방지한다.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/ubuntu/Development-Support
            git pull
            cd /home/ubuntu/Development-Support/frontend
            npm install
            npm run build
            cd /home/ubuntu/Development-Support/backend
            npm install
            nohup npm run start </dev/null >/dev/null 2>&1 &
